version: '3.8'
services:
  dev-shadow-db:
    image: postgres:13
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: lc-db
    networks:
      - local
networks:
  local: